
env:
   global:
     - CONAN_USERNAME: rikdev
     - CONAN_LOGIN_USERNAME: rikdev
     - CONAN_UPLOAD: https://api.bintray.com/conan/rikdev/conan

linux: &linux
   os: linux
   dist: bionic
   language: python
   python: 3.7
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8

      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=7.0 CONAN_DOCKER_IMAGE=conanio/clang7

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/clang8

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=x86_64 CONAN_DOCKER_IMAGE=conanio/android-clang8

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=armv8 CONAN_DOCKER_IMAGE=conanio/android-clang8-armv8

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=x86 CONAN_DOCKER_IMAGE=conanio/android-clang8-x86

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_ARCHS=armv7 CONAN_DOCKER_IMAGE=conanio/android-clang8-armv7

      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0

      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
